# Generated by Django 5.2.5 on 2025-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Enter your name')),
                ('age', models.IntegerField(max_length=2, verbose_name='Enter your age')),
                ('dob', models.DateField(verbose_name='Enter your DOB')),
                ('mobile', models.CharField(max_length=12, verbose_name='Enter your number')),
                ('email', models.EmailField(max_length=25, verbose_name='Enter your email')),
                ('city', models.CharField(max_length=30, verbose_name='Enter your city')),
                ('website', models.URLField(max_length=50, verbose_name='Enter your website')),
                ('degree', models.CharField(max_length=50, verbose_name='Enter your degree')),
                ('profile', models.CharField(max_length=50, verbose_name='Enter your profile')),
                ('shor_desc', models.TextField(max_length=150, verbose_name='Enter your description')),
                ('desc', models.TextField(max_length=150, verbose_name='Enter your description')),
                ('pimg', models.ImageField(upload_to='', verbose_name='Enter your img')),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Eduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=30, verbose_name='enter your degree ')),
                ('year', models.CharField(max_length=6, verbose_name='enter years')),
                ('clgname', models.CharField(max_length=30, verbose_name='enter your clg name')),
                ('desc', models.TextField(max_length=300, verbose_name='enter your decs')),
            ],
            options={
                'db_table': 'eduction',
            },
        ),
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=30, verbose_name='enter your profile ')),
                ('year', models.CharField(max_length=6, verbose_name='enter years')),
                ('company', models.CharField(max_length=30, verbose_name='enter your company name')),
                ('desc', models.TextField(max_length=300, verbose_name='enter your decs')),
            ],
            options={
                'db_table': 'experince',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=40, verbose_name='enter your skills;')),
                ('rate', models.IntegerField(max_length=5, verbose_name='enter your rate of skills in persantage')),
                ('desc', models.TextField(max_length=300, verbose_name='enter you descripseion')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
