# Generated by Django 5.2.5 on 2025-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='freelance',
            field=models.CharField(default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=models.TextField(verbose_name='Enter your description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='shor_desc',
            field=models.TextField(verbose_name='Enter your description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='website',
            field=models.CharField(max_length=50, verbose_name='Enter your website'),
        ),
        migrations.AlterField(
            model_name='eduction',
            name='clgname',
            field=models.CharField(max_length=50, verbose_name='enter your clg name'),
        ),
        migrations.AlterField(
            model_name='eduction',
            name='year',
            field=models.CharField(verbose_name='enter years'),
        ),
    ]
