# Generated by Django 5.2.5 on 2025-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_about_freelance_alter_about_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Portfolio Title')),
                ('desc', models.TextField(max_length=500, verbose_name='Portfolio Description')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Portfolio Image')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Portfolio Title')),
                ('desc', models.TextField(max_length=500, verbose_name='Portfolio Description')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
