# Generated by Django 5.2.5 on 2025-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_portfolio_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='experince',
            name='work',
            field=models.CharField(default='Developer', max_length=200),
        ),
    ]
