# Generated by Django 5.2.5 on 2025-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_experince_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='experince',
            name='desc1',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='experince',
            name='year',
            field=models.CharField(max_length=25, verbose_name='enter years'),
        ),
    ]
