# Generated by Django 5.2.5 on 2025-09-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_experince_desc1_alter_experince_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mapurl',
            field=models.URLField(default='see url', max_length=400),
        ),
    ]
