# Generated by Django 5.2.5 on 2025-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_about_mapurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='about',
            name='sumdes',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Enter your email'),
        ),
    ]
