# Generated by Django 5.2.5 on 2025-09-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_delete_portfolio_delete_services_about_sumdes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='experince',
            name='profile',
        ),
        migrations.AddField(
            model_name='about',
            name='condes',
            field=models.TextField(default='Not Provided'),
        ),
    ]
