# Generated by Django 5.2.5 on 2025-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_remove_about_profile_remove_experince_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='enter name')),
                ('email', models.CharField(max_length=50, verbose_name='enter email')),
                ('subject', models.CharField(max_length=60, verbose_name='enter subject')),
                ('message', models.TextField(verbose_name='enter message')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
